apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: sentinelopsai
  labels:
    app: mongodb
    app.kubernetes.io/part-of: sentinelopsai
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: "mongodb"
      port: 27017
      targetPort: 27017
