apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-service
  namespace: sentinelopsai
  labels:
    app: collector-service
    app.kubernetes.io/part-of: sentinelopsai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector-service
  template:
    metadata:
      labels:
        app: collector-service
    spec:
      containers:
        - name: collector-service
          image: maheshkumars772/sentinelops-collector-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
