apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: sentinelopsai
  labels:
    app: collector-service
    app.kubernetes.io/part-of: sentinelopsai
spec:
  type: ClusterIP
  selector:
    app: collector-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
